### ISSUE TITLE
Standardize the use of keys for course settings

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/coursemology2#1063]
Currently there is no mechanism to ensure/enforce the keys on `course.settings`. To think about how we can fix this to reduce developer errors (when settings' keys are spelt wrongly).

**Comment by lowjoel** [comment]
I believe each component is supposed to have its own namespace. Then the keys are restricted to its own namespace and it just has to be internally consistent.

Unless you're referring to something else here, maybe you'd like to elaborate?

**Comment by allenwq** [comment]
There are some places the keys are used externally, such as  this case:
https://github.com/Coursemology/coursemology2/blob/master/app/controllers/components/course/announcements_component.rb#L14
https://github.com/Coursemology/coursemology2/blob/master/app/controllers/course/admin/announcement_settings_controller.rb#L25

The two `:announcement` symbol must be exactly same, otherwise they are referring different settings

**Comment by lowjoel** [comment]
I think components should provide an API for access to their hash, in that case.

**Comment by allenwq** [comment]
Fixed by #2306
