### ISSUE TITLE
My courses page 

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#1113]
A page shows all my courses:
 - Separate Active course and completed course

**Comment by kxmbrian** [comment]
As discussed with @allenwq, it might not be very beneficial to separate "Course you are attending" and "Courses you are teaching" in the "My Courses" listing. 

Firstly, a large number of users are likely to have only one course. Secondly, for those who have multiple courses, it is likely that they are either a teacher or student (in real life) and hence have either one, but not both kinds of courses.

For those with both, e.g. university tutors, they will likely juggle between only a few courses, and will be looking for a course directly, rather than for the category (i.e. "attending" or "teaching") then the course name.

It is more important to ensure that the recent/active courses are more easily accessible than older ones.
