### ISSUE TITLE
Add navbar icons to navbar

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1375]
Just like v1

**Comment by cysjonathan** [comment]
Because Assessments categories can be created by course admin in any course, it's virtually impossible place **different** navbar icons for "Missions" and "Trainings" or any other assessment.

![selection_016](https://cloud.githubusercontent.com/assets/10083037/18232299/5a8805a4-72ff-11e6-80a4-e21033174e9c.png)

Some options:
a) assign them a default icon for all assessments (See pic)
b) add feature to allow them to pick (immutable) icons when creating of their assessment (need GUI?)
c) eventually, add feature allow them to modify current icon to another icon?

(a) can be implemented immediately.
We can skip (a) and move to (b), but it will take some time...

**Comment by benleong** [comment]
I don't like (b). We can start with (a) and extend to (c) later. Thanks.

**Comment by benleong** [comment]
Key is to ensure that we set up the models/dbase to allow for extension to
(c) later without any further changes to the dbase.
