### ISSUE TITLE
Flag out programming language selector if nothing has been chosen

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1508]
When creating a programming question, when no language is selected and "Create Programming" is clicked, nothing happens.

This is confusing for the user who may not know whether he didn't click the button or if something else went wrong.

Highlight the selector or show a flash message to indicate that a programming language must be selected.

**Comment by weiqingtoh** [comment]
@fonglh you can try solving this by adding a validation at the model then adding the error message. The form should pick up the error message automatically. Give it a try?

**Comment by fonglh** [comment]
That doesn't work. It seems to fail on the client side.

`An invalid form control with name='question_programming[language_id]' is not focusable.`

**Comment by weiqingtoh** [comment]
This is quite an nasty issue - turns out all browsers also try to do client-side validation by inferring the HTML tags. 

What happens is that when `simple_form` tries to build it form, it has this kind of structure:
```html
<div class="form-group select required question_programming_language">
  <label>Form heading etc.</label>
  <select class="select required form-control" required="required" aria-required="true" name="question_programming[language_id]" id="question_programming_language_id" style="display: none;">Options etc.</select>
  <div>
    <button> dropdown options and text here</button>
  </div>
</div>
```

The select tag is hidden (ie. 'display: none') here, but stated as a required attribute. This results in:
- Validation working okay on Safari;
- Validation being buggy on Firefox (tooltip is not where it should be); and 
- Validation not allowing the form to be submitted on Chrome. 

Some related readings: [simple_form issue](https://github.com/plataformatec/simple_form/issues/440), [short post on it](https://tiffanybbrown.com/2015/11/an-invalid-form-control-is-not-focusable/index.html), [stackoverflow](http://stackoverflow.com/questions/7168645/invalid-form-control-only-in-google-chrome).

Based on this, it might make sense to disable client-side validation and rely on server-side first, then figure out how to bend `simple_form` to figure out the correct HTML structure so that we can use client-side validation.

Thoughts? @allenwq @fonglh

**Comment by fonglh** [comment]
Kick the can down the road? I think server side validation is fine. Although I'm not sure what happens to the uploaded package. Does it end up getting stored for all eternity and orphaned?

I think our filestore was designed to be immutable. @allenwq can shed some light on this?

**Comment by allenwq** [comment]
@weiqingtoh I think this is a quite common issue across all forms, the programming language is not the only one. 

And if you disable javascript, there won't be any client side validations. But with javascript enabled, different browser does different things.

**Comment by weiqingtoh** [comment]
Between having somewhat varying (or even broken) client-side validations vs a more consistent server-side form validation, I tend to prefer the latter. 

If not, we will get users who keep trying to submit but not know what the issue is, which can be frustrating.

**Comment by allenwq** [comment]
@weiqingtoh Yes I agree. My point is we might need to change the global config of simple_form, every form got this problem.

**Comment by kxmbrian** [comment]
This is not a problem for assessments since the move to react in #2354.
Another issue can be opened for other forms if the need arises.
