### ISSUE TITLE
Hide 'Run code' button when there are no test cases

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1793]
Programming questions are not autogradeable when there are no test cases. In these situations, the 'Run code' button should be hidden from students.

Consider what to do if there are only evaluation tests. Staff should be able to run the tests, but students should see it as not autogradeable or it will be confusing.

**Comment by weiqingtoh** [comment]
I'll work on hiding the button if the question has no tests. 

I'm not sure if it's ever wise to design a question such that there are no public and private tests, and only evaluation tests. Not that this is hard to change, but I suspect it will cause more harm than good (imagine what if all the tutors received programs which can't even run). 

Thoughts? @fonglh @allenwq

**Comment by fonglh** [comment]
I think we should assume someone will do it. So the button should be hidden from students if there are no public nor private tests.

Hidden from staff if there are no tests at all.

**Comment by allenwq** [comment]
There are questions only have evaluation tests, I remember one of the Hungry Game questions ?

**Comment by allenwq** [comment]
Think we should hide the button for both cases for students, they cannot see any feedback when press the button. 

For staff side, they will see the evaluation test results after students submitted. But before the student submits the submission, I lean to hide them as well. Otherwise it will likely confuse staff cause the view are inconsistent.
