### ISSUE TITLE
Notify students by comments bubble when instructors make a comment on their work

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#1883]
When testing the emails, the comments bubble does not work when an instructor comments on the student's work.

**Comment by allenwq** [comment]
On the student side it's not implemented, it can be implemented using Read/Unread

**Comment by cysjonathan** [comment]
Bumping this issue because students don't know when they are getting replies/comments (unless they regularly check their comments). Also, it's not apparent to instructors that their students don't have notification bubbles, since instructor themselves have working notification bubbles.

Demonstration of missing feature:
Instructor screen on top, student screen below.
![no_comment_notification_bubble](https://user-images.githubusercontent.com/10083037/34650655-a87deb5c-f3ff-11e7-92af-e63e78c279f8.gif)

Instructors are getting notification bubbles, but students are not.
This is only for comments.

Forums notification bubbles are working fine.
