### ISSUE TITLE
Add "Opened" to "Submission status" for assessment

### ISSUE THREAD

**Issue by luoyanjie** [Coursemology/coursemology2#2030]
When student opened an assessment (i.e. click on asesssment name), the submission status for that student's assessment should be "opened".

Update Wai Kay when done.

**Comment by weiqingtoh** [comment]
Things to consider 
 - What if assessment has no files? 
 - There is a lead on, where sometimes the template files are only shown in the submission, rather than uploaded as a file? How can we handle this? 
 - Should we track if student downloaded files, or only opened assessment? 
 - What if student download files from lesson_plan page?

**Comment by luoyanjie** [comment]
Decided to use another UI fix instead.
