### ISSUE TITLE
Answer states inconsistent with submissions

### ISSUE THREAD

**Issue by allenwq** [Coursemology/coursemology2#2046]
In some race conditions, answer states get inconsistent with submissions. ( e.g. a graded submission could have an attempting answer ).

This could result in autograded submissions cannot be graded.

**Comment by weiqingtoh** [comment]
@allenwq is correct in that this is a race condition, and that 2 requests are sent: (i) one to finalize submission, (ii) one to evaluate the answer. Because both don't know about each other it results in out of out of sync answer states with submissions.

Leaving some investigation findings here: 
```
### Sample Submission: 32970 (All dates were 1 Feb 2017)

## Logs on 1-Feb-2017 from 14:28:05 to 14:28:35 with 32970:
4 Requests were made - from 4 request IDs:
14:28:12.157 - 1975658fe3f4 - POST to update submission (enqueued job ID - 80afe4d5-a9b6-4bfe-b840-b6b6d745147c - last call to jobs/:id was at 14:28:17.992)
14:28:16.816 - 30f6c97c24a5 - POST to update submission - with Finalize Submission param (enqueued job ID - d68192f3-da3d-4ca1-bb5c-5e322febd5d0 - job started 14:28:17.449)
14:28:17.534 - fb957b8d3f6f - Reload to submission edit page (Probably from the finalize submission)
14:28:18.110 - 0c2f541bf90c - POST to reload answer (id 463836 - probably from the submission update, which is request 1975658fe3f4)

My guess is 2 tabs were open: 
## Tab 1 - User executed code here.
14:28:12.157 - 1975658fe3f4 - POST to update submission (enqueued job ID - 80afe4d5-a9b6-4bfe-b840-b6b6d745147c - last call to jobs/:id was at 14:28:17.992)
14:28:18.110 - 0c2f541bf90c - POST to reload answer (id 463836 - probably from the submission update, which is request 1975658fe3f4)

## Tab 2 - User finalized submission here
14:28:16.816 - 30f6c97c24a5 - POST to update submission - with Finalize Submission param (enqueued job ID - d68192f3-da3d-4ca1-bb5c-5e322febd5d0 - job started 14:28:17.449)
14:28:17.534 - fb957b8d3f6f - Reload to submission edit page (Probably from the finalize submission)
```

**Comment by weiqingtoh** [comment]
Had a fruitful discussion with @allenwq and the conclusion to fix the race condition is as follows: 
 - Before creation of a new answer when the `Submit` button is pressed, reload the submission and check whether the submission state is `submitted`. 
 - In the submission auto-grading job: (i) reload the submission and check whether all `latest_answers` are graded, otherwise regrade answers, and (ii) handle cases where any of the `latest_answers` is in a attempting state.

This will prevent the race condition because:
 - A new answer is only created when the submission is not `submitted` and in the attempting state; and 
 - The autograder job could handle the case where a new answer was created, and also ensure that all new answers that were created after the job starts is graded.
