### ISSUE TITLE
Add button "Publish Grade+Find Next"

### ISSUE THREAD

**Issue by benleong** [Coursemology/coursemology2#2533]
This will make it more convenient for the tutors when they grade. Basically after grading an assesssment manually, this will bring up the next submitted assessment on one's pending grading list.

**Comment by luoyanjie** [comment]
I disagree with this feature. It is bad UX. 
This is because after clicking "save", one needs affirmation and assurance that what they've saved is saved. 

Right now the assurance is given via the toast. The toast cannot appear in the next page as it will give the wrong idea that it is the new page which has been saved. That is quite scary.

Instead, what we need is a left and right link to allow teaching staff to easily jump to the next or previous assignment. This will solve the issue and give teaching staff an easy way to browse through submissions.

**Comment by luoyanjie** [comment]
Also, this will allow any permutation of action + go on to the next one. IF not later we have to build "save + find next", "unsubmit + find next" etc.

**Comment by benleong** [comment]
OK. Let's kill this idea.
