### ISSUE TITLE
Autograded programming questions cannot be edited with Safari

### ISSUE THREAD

**Issue by fonglh** [Coursemology/coursemology2#2962]
When a change is made and the "Submit" button is clicked to save the changes, an error message toast comes up.

When tested on local development, the spinner button spun forever. No request reached the server.

@allenwq investigated and suspects it's a browser compatibility issue with `FormData`.

``` 
onSubmit = (e) => {
    e.preventDefault();
    if (!this.validationCheck()) return;

    const url = this.props.data.getIn(['form_data', 'path']);
    const method = this.props.data.getIn(['form_data', 'method']);
    const formData = new FormData(this.form);
```

This assumes that `FormData` magically extracts everything from `this.form`. There might be browser differences in this API.

A possible solution is to refactor this to submit JSON instead of `FormData`, which is what Survey questions and other components are already doing.

Non autograded questions are still ok. The complexity of the autograded programming question form may be causing an issue.

**Comment by jeremyyap** [comment]
There are helper functions in other components to build FormData from javascript objects:

https://github.com/Coursemology/coursemology2/blob/a44c419f6419772315834e5af97a3f39f46b213c/client/app/api/course/Assessment/Submissions.js#L69

https://github.com/Coursemology/coursemology2/blob/a44c419f6419772315834e5af97a3f39f46b213c/client/app/api/course/Assessment/Submission/Answer/Programming.js#L56

https://github.com/Coursemology/coursemology2/blob/a44c419f6419772315834e5af97a3f39f46b213c/client/app/api/course/Assessment/question/scribing/Scribing.js#L37

The first two (which I just realised were copy-pasted) were written to be quite general, will have to try it out on the programming question edit page to see if it can be used though.

**Comment by jeremyyap** [comment]
Found the cause, FormData submission fails on Safari when there is an empty `input[type=file]` in the FormData. This is due to a [regression in WebKit](https://trac.webkit.org/changeset/230963/webkit).

The following Stack Overflow threads contain several proposed solutions to work around this bug:

https://stackoverflow.com/questions/49672992/ajax-request-fails-when-sending-formdata-including-empty-file-input-in-safari

https://stackoverflow.com/questions/49614091/safari-11-1-ajax-xhr-form-submission-fails-when-inputtype-file-is-empty
