### ISSUE TITLE
Text editor parsing formatting info as text

### ISSUE THREAD

**Issue by trangmei** [Coursemology/coursemology2#3054]
To reproduce issue:
Copy-paste formatted text to Mac Notes, then command+A and copy-paste back to coursemology (new forum post).
The formatting tags is only visible when 'code view' is enabled.
When posted this formatting tags will appear as text.

Issue not observed when copy-pasting from one coursemology page to another. Looks like the formatting tags are appended by Notes.

- [ ] remove weird content from https://coursemology.org/courses/1346/forums/writing-assignment-1-what-do-you-hope-to-learn-in-cs3216/topics/my-expected-learnings
- [ ] find root cause
- [ ] prevent future occurrence

**Comment by trangmei** [comment]
Looks like Summernote edit view show the pasted text as-is, i.e.: <p><style>gibberish</style></p>. 'gibberish' is hence invisible.
While forums/:/topics/: view removes <style></style> tags but not the text in between before displaying, hence 'gibberish' is visible.

**Comment by jeremyyap** [comment]
`SANITIZATION_FILTER_WHITELIST` specifies which tags and attributes are allowed through, this line allows the style attribute in any html tag, eg:

```html
<span style="color: red;"></span>
```

I think `<style>` tags are not whitelisted, that's why it's being stripped. Default whitelist is [here](https://github.com/jch/html-pipeline/blob/642e9226929fa667e3513233c130186195880b24/lib/html/pipeline/sanitization_filter.rb#L40), which `SANITIZATION_FILTER_WHITELIST` extends.
