### ISSUE TITLE
Duplication spinner goes on forever

### ISSUE THREAD

**Issue by aaronhojw** [Coursemology/coursemology2#3230]
Investigate why the background process doesn't signal its completion.
Possible that the frontend loops crashes if one of the refreshes times out.

**Comment by trangmei** [comment]
@aaronhojw can you provide link to the item you were trying to duplicate?

**Comment by trangmei** [comment]
When duplicating big courses, course duplication job might take longer than nginx timeout.
This might be the cause of spinner wheel going on forever.

- [ ] To reproduce this on local.

Proposed solution: Since email notification is sent after course duplication completes, we can consider removing spinner wheel entirely and replacing it with a static page informing user to wait for email notification. This requires email to be sent when the job fails as well, for the user to close the loop. Drawback of this solution is that duplication of smaller courses would not redirect to the new course upon successful completion.

**Comment by aaronhojw** [comment]
> @aaronhojw can you provide link to the item you were trying to duplicate?

It usually happens for large-sized courses or assessments.
Do you still need me to find you a sample link so you can see it happening? If so, I'll probably go look for something big and try to duplicate it before sending you the item's link.

**Comment by trangmei** [comment]
@aaronhojw no worries Li Heng already explained to me the problem.

We'll put something in to smoothen the UX when we have time.
