### ISSUE TITLE
Missing 'unsubscribe successfully' view

### ISSUE THREAD

**Issue by trangmei** [Coursemology/coursemology2#3393]
Unsubscribing to Forum using email link => Page not found.

Should go to a page saying "Unsubscribed successfully from Forum XXX".

**Comment by jeremyyap** [comment]
Clicking an `Unsubscribe` link in an email actually makes a GET request to the unsubscribe endpoint but the server only accepts DELETE requests. That's why it returns 404.

- One way to embed a DELETE link in an email is to use a form, but that's not supported by many email clients.

- It's probably not a good idea to create a GET action which deletes the subscription since GET requests should be idempotent.

- A proper solution would be to link to a page with an unsubscribe button for the user to click. In this case it would be the forum index page itself. However that would be an extra click and page load for the user.

**Comment by jeremyyap** [comment]
Oh, it's using the GET action to unsubscribe here https://github.com/Coursemology/coursemology2/blob/master/config/routes.rb#L298

In that case maybe we can just add a redirect to index and show a flash message.

**Comment by benleong** [comment]
get would also be idempotent because you cannot unsubscribe twice.

**Comment by jeremyyap** [comment]
Oops, I meant safe, as in GET requests shouldn't change data on the server. But since the current implementation is already not safe, we can leave it as it is.
