### ISSUE TITLE
Add error message when autograding times out

### ISSUE THREAD

**Issue by trangmei** [Coursemology/coursemology2#3566]
Some programming questions take longer than 10s (default time limit) to grade. From the UI this looks like none of the test cases have been graded.

Stdout and stderr are not informative enough to suggest users increase time limit.

To add a more informative error message.

**Comment by rrtheonlyone** [comment]
I believe the root cause for this issue is the bash program that is run in the containers that handle the evaluation (https://github.com/Coursemology/evaluator-images/blob/master/base/usr/local/bin/coursemology-evaluate.sh)

It is not easy to check if a task got killed from the error message from the child process. We use `ulimit` to set a threshold and the `make` script will return an exit code of `2` : This is ambiguous and not enough information to deduce if a task timed out.

One solution I figured was to just to catch the error message from `stderr` in the bash script and modify if the error message contains "Killed". Script Reference: https://gist.github.com/rrtheonlyone/8b9fd5a80491aacecbda865f958a2cdf

The stderr message previously was like this:
```
Killed
make: *** [public] Error 137
```

After my improvement, the `stderr` message will be like this:
```
The program was killed.
It probably took too long to run (time limit: 1 s).
There is also a memory limit of unlimited kb.
```

If this is a feasible solution (or an improvement over existing system), I can go ahead to make a PR! Do also let me know if you feel there is a better way to handle this.

**Comment by trangmei** [comment]
Issue could not be reproduced locally, and is no longer observed after more memory is allocated to worker servers.
The root cause is likely resource constraints.
