### ISSUE TITLE
Newly created achievements not awarded when the requirements have been reached beforehand

### ISSUE THREAD

**Issue by ekowidianto** [Coursemology/coursemology2#4038]
When a new achievement is created, if a student has fulfilled the requirements before the achievement is created, it is not automatically awarded to the student.

**Comment by zhuhanming** [comment]
Yes, this is actually quite a tricky issue, and is due to when the conditional graph is recomputed. I suspect a recomputation is only done at specific moments to restrict resource usage.

Another bug is: if an achievement's condition is changed, a student who previously obtained the achievement and no longer meets the new conditions will still retain the achievement.
