### ISSUE TITLE
Submissions view page slow to render for large classes

### ISSUE THREAD

**Issue by cysjonathan** [Coursemology/coursemology2#4166]
When class is large the frontend takes a long time to render.
Related to discussion in #4137 and possible solutions would be to
1. collapse buttons into a single context ⋮ button, or
2. remove all buttons ansd use a checkbox instead to perform mass actions instead

Example of long loading time
https://coursemology.org/courses/1935/assessments/38707/submissions

**Comment by ekowidianto** [comment]
The main culprit for this issue is that there are too many tooltips rendered and after further investigation, the page is inherently slower when there are no submissions from the students. Upon investigation, this is caused by the unsubmit and delete tooltips and buttons in the page not having unique ids (submission id was used and it is null when there is no submission) and hence, each button is pointing to all other tooltips.

The page will be further optimized by only rendering 1 tooltip for each button type (eg delete button) for all rows and each button in different rows will be referring to the same tooltip.
