### ISSUE TITLE
Add (back?) file name for programming question box

### ISSUE THREAD

**Issue by RichDom2185** [Coursemology/coursemology2#7544]
Some students are getting confused at what the extra boxes are for because it's not clear that it's to upload/copy separate files. Moreover, for both the students and graders it's very hard to tell which template/box belongs to which file.

Just took a look at the student submissions, the file contents are all pasted in the wrong locations as a result. This particular assessment doesn't have test cases that involve compiling these files, which are reliant on them being in the correct file name, so I can't say for certain if this will be a major issue.

Hovering over the download links also don't show any link preview, you actually have to click it to see the file you just downloaded:

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/d81134e8-c296-43a5-9bad-e19de5913e01">

I seem to recall the file names being visible, and I tried to trace the commits, but between all the refactoring going on, I can't find what seems to have caused this.

Would kindly appreciate a quick response, thanks!

**Comment by cysjonathan** [comment]
Hi Richard, for instructors, it has always been a view with all the individual files laid out like this for many years.  
For students, they should see chips to toggle between files, but we are checking why they do not see chips in your case, and if there is a better UI for both students AND teachers.

1. Ensure each code box has an associated Filename for multi-file answers
2. Fix student view to ensure they can clearly distinguish between files
3. Determine then implement the best view(s) for students / instructors (not necessarily the same view, since instructors need a view for grading)

**Comment by syoopie** [comment]
Temp fix in #7550
