### ISSUE TITLE
Reorganize experience points models

### ISSUE THREAD

**Issue by kxmbrian** [Coursemology/coursemology2#825]
Since the same manual EXP award is usually given to multiple students, would it be better to use the follow design instead? : 

```ruby
class Course::ExperiencePoints::Record
  # remove attr reason
  attr points_awarded
end

class Course::ExperiencePoints::AdhocRecord
  acts_as_experience_points_record
  belongs_to course_experience_points_adhoc_award
  belongs_to user
end

class Course::ExperiencePoints::AdhocAward
  attr reason
  has_many course_experience_points_adhoc_record
  belongs_to course
end
```

This might make it easier to correct mistakes when manually awarding EXP, e.g. typo in reason, missed out students.

For the existing design, an `ExperiencePointsRecord` belongs to a `CourseUser`, but we can potentially also reach the `CourseUser` by via `exp_record.actable` (e.g. via a submission). I think it might be good to normalise this. Any concerns if I do?

If we go ahead with the normalization, should we somehow enforce that if a class `acts_as_experience_points_record`, it should respond to `course_user`? Along with that, perhaps also enforce that each should implement a method `experience_points_record_description` that returns a string for display in the EXP history.

**Comment by lowjoel** [comment]
I can't remember why we elected to stick to the current design. Submissions do not have course users, check the database schema.

I think we have the current design because the reason field is really not used much except when displaying. Even in those circumstances, the reason is normally going to be generated by the actable object. So the additional join is not necessary.

**Comment by lowjoel** [comment]
@kxmbrian does this still need fixing?

**Comment by kxmbrian** [comment]
We can close this
