### ISSUE TITLE
Replace the use of translation strings for fields with human_attribute_name

### ISSUE THREAD

**Issue by lowjoel** [Coursemology/coursemology2#832]
Instead of manually translating model property names in views, use the model's  human_attribute_name method, e.g. `@submission.class.human_attribute_name(:grade)`

**Comment by ZitaNemeckova** [comment]
@lowjoel How does it originally look like? Not sure what should be replaced. Thanks :)

**Comment by weiqingtoh** [comment]
@ZitaNemeckova Before -> https://github.com/Coursemology/coursemology2/pull/1110#r67801262 - you can see the code segment that is outdated.

After -> https://github.com/Coursemology/coursemology2/pull/1110/commits/063d9b04fa532b9a9197287a2cad92946ca4a396#diff-397cf46bb6abf694e38351c00262b9a0R5

It will be a little painful to find some of them (since we do have quite a few partials), but you can start with the `views/course` folder. I suspect most of them are either table header rows, or forms.  If you are unsure of whether a particular partial requires this change, feel free to drop me a note (and tag me here), or join our slack group and ping there first.

**Comment by ekowidianto** [comment]
Closing as we are porting to React
